#
# ### Continueous Deployment
#
# Ensure that code successfully builds passes tests, and deploy it
#
# Required parameters
#   - azureServiceConnectionName: Service connection to use for deployment
#   - azureAppServiceName: Name of app service
#

trigger:
  branches:
    include:
    - main
    - master

variables:
- template: vars/vars-all.yaml
- template: vars/vars-cd.yaml

stages:

#
# Build, test and publish solution
#

- stage: Build
  displayName: 'Build'

  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: windows-latest

    steps:
    - template: steps/git-checkout.yaml
    - template: steps/build-test.yaml
    - template: steps/publish.yaml

#
# Deploy to Azure App Service
#

- stage: Deploy
  displayName: 'Deploy'
  dependsOn: Build
  condition: succeeded()

  jobs:
  - job: Deploy
    displayName: 'Deploy Website'
    pool:
      vmImage: windows-latest

    steps:
    - template: steps/deploy-appservice.yaml
      parameters:
        appType: 'webApp'
